export enum TileType {
    EMPTY,

    NORTH,
    SOUTH,
    EAST,
    WEST,

    NORTH_EAST,
    NORTH_WEST,
    SOUTH_EAST,
    SOUTH_WEST,

    NORTH_SOUTH_EAST,
    NORTH_SOUTH_WEST,
    EAST_WEST_NORTH,
    EAST_WEST_SOUTH,

    NORTH_SOUTH_EAST_WEST,
    NORTH_SOUTH_HOPS_EAST_WEST,
    EAST_WEST_HOPS_NORTH_SOUTH,
}